[package]
name = "node_ws"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
tokio-tungstenite = "0.26"
futures-util = "0.3"
serde_json = "1.0"
tungstenite = "0.26"
ureq = "3.0"
sysinfo = { version = "0.35", features = ["multithread"] }
serde = { version = "1", features = ["derive"] }
url = "2"
hostname = "0.4"
