[package]
name = "rust_gui"
version = "0.1.0"
edition = "2021"
description = "GUI dashboard for Lumaris Marketplace seller nodes"

[dependencies]
eframe = { version = "0.23", features = ["wgpu"] }
egui = "0.31"
serde = { workspace = true }
serde_json = { workspace = true }
tungstenite = { workspace = true }
url = { workspace = true }
hostname = { workspace = true }
ureq = { workspace = true }
sysinfo = { workspace = true }
winapi = { version = "0.3.9", features = ["sysinfoapi", "minwindef", "processthreadsapi"] }
log = { workspace = true }
env_logger = { workspace = true }
thiserror = { workspace = true }
