[package]
name = "rust_gui"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = { version = "0.23", features = ["wgpu"] }
egui = "0.31"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tungstenite = "0.21"
url = "2.4"
hostname = "0.3"
ureq = "2"
sysinfo = "0.29"
winapi = { version = "0.3.9", features = ["sysinfoapi", "minwindef", "processthreadsapi"] }
