name: Django CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    name: Run Django tests on Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.9]
      max-parallel: 4

    steps:
      # ✅ Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v4

      # ✅ Set up the requested Python version
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      # ✅ Restore pip cache
      - name: Restore pip cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # ✅ Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r lumaris_frontend/requirements.txt

      # ✅ Run Django tests
      - name: Run tests
        working-directory: lumaris_frontend
        env:
          DJANGO_SETTINGS_MODULE: lumaris_frontend.settings
        run: |
          python -m pytest -v marketplace/tests/test_jobs.py

